apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: edc2021-radix-client-cert
spec:
  environments:
    - name: "off"
      build:
        from: main
    - name: optional-no-ca
      build:
        from: TEST
    - name: optional
      build:
        from: QA
    - name: "on"
      build:
        from: ON
  components:
    - name: api
      src: api
      ports:
        - name: http
          port: 5000
      publicPort: http
      authentication:
        clientCertificate:
          verification: "on"
          passCertificateToUpstream: true
      variables:
        ASPNETCORE_URLS: "http://*:5000"
      environmentConfig:
        - environment: "off"
          authentication:
            clientCertificate:
              verification: "off"
        - environment: optional-no-ca
          authentication:
            clientCertificate:
              verification: "optional_no_ca"
        - environment: optional
          authentication:
            clientCertificate:
              verification: "optional"
